name: Compile YellProgram

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Libraries
      run: |
        set -e
        
        setup_lib() {
          mkdir -p lib/$1
          cd lib/$1
        }

        # Compile levmar
        setup_lib levmar
        curl -LOv --user-agent "Mozilla/5.0" http://users.ics.forth.gr/~lourakis/levmar/levmar-2.6.tgz
        tar -zxf levmar-2.6.tgz
        mkdir levmar-build
        cd levmar-build
        cmake --help
        cmake -G "Unix Makefiles" -DNEED_F2C:BOOL=0 -DBUILD_DEMO:BOOL=0 -DLAPACKBLAS_LIB_NAMES:STRING=" -framework accelerate" -DCMAKE_CONFIGURATION_TYPES:STRING="Release" ../levmar-2.6
        cmake --build .

        # Setup boost
        setup_lib boost
        curl -LOv --user-agent "Mozilla/5.0" https://yer.dl.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.zip
        unzip boost_1_60_0.zip
        mv boost_1_60_0/boost .

        # Setup cxxtest
        setup_lib cxxtest
        curl -LOv --user-agent "Mozilla/5.0" https://yer.dl.sourceforge.net/project/cxxtest/cxxtest/4.4/cxxtest-4.4.tar.gz
        tar -zxf cxxtest-4.4.tar.gz
        mv cxxtest-4.4/* .

        # Setup LAPACK
        setup_lib lapack
        curl -LOv --user-agent "Mozilla/5.0" https://www.netlib.org/lapack/lapack-3.6.0.tgz
        tar -zxf lapack-3.6.0.tgz
        mkdir lapack-build
        cd lapack-build
        cmake -G "Unix Makefiles" ../lapack-3.6.0
        cmake --build .

    - name: Setup and Compile Boost
      run: |
        set -e
        mkdir -p lib/boost
        cd lib/boost
        curl -LOv --user-agent "Mozilla/5.0" https://yer.dl.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.zip
        unzip boost_1_60_0.zip
        cd boost_1_60_0
        #./bootstrap.sh
        #./b2 --prefix=${GITHUB_WORKSPACE}/lib/boost install

    - name: List Boost headers
      run: |
        ls -la ${GITHUB_WORKSPACE}/lib/
        ls -la ${GITHUB_WORKSPACE}/lib/levmar
        ls -la ${GITHUB_WORKSPACE}/lib/levmar/levmar-build
        
#    - name: Check if file exists
#      run: |
#        ls -la ${GITHUB_WORKSPACE}/lib/cctbx_stubs/cctbx/sgtbx/
#        if [[ ! -f ${GITHUB_WORKSPACE}/lib/cctbx_stubs/cctbx/sgtbx/change_of_basis_op.cpp ]]; then
#          echo "File does not exist!"
#          exit 1
#        else
#          echo "File exists!"
#         fi

   

    - name: Compile Yell
      run: |
        set -e
        rm -rf yell-build
        mkdir yell-build
        cd yell-build
        cmake -G "Unix Makefiles" -DCMAKE_CXX_FLAGS:STRING="-I${GITHUB_WORKSPACE}/lib/boost" ..
        make
