name: Compile YellProgram

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: List directories for debugging
      run: |
        pwd
        ls -al
        
    - name: Setup HDF5
      run: |
        mkdir -p lib
        cd lib
        rm -rf hdf5-1.8.6  # This ensures the directory is cleared if it exists
        tar -xf ../hdf5-1.8.6.tar
        cd hdf5-1.8.6
        ./configure --prefix=$(pwd)/../hdf5-install 2> hdf5_configure_errors.log
        make 2> hdf5_make_errors.log
        make install 2> hdf5_make_install_errors.log
      shell: /usr/bin/bash -e {0}

    - name: Setup Libraries
      run: |
        set -e
        
        setup_lib() {
          cd lib
          mkdir -p $1
          cd $1
        }

        # Compile levmar
        setup_lib levmar
        curl -LOv --user-agent "Mozilla/5.0" http://users.ics.forth.gr/~lourakis/levmar/levmar-2.6.tgz
        tar -zxf levmar-2.6.tgz
        mkdir levmar-build
        cd levmar-build
        cmake -G "Unix Makefiles" -DNEED_F2C:BOOL=0 -DBUILD_DEMO:BOOL=0 -DLAPACKBLAS_LIB_NAMES:STRING=" -framework accelerate" -DCMAKE_CONFIGURATION_TYPES:STRING="Release" ../levmar-2.6
        make

        # Setup boost
        setup_lib boost
        curl -LOv --user-agent "Mozilla/5.0" https://yer.dl.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.zip
        unzip boost_1_60_0.zip
        mv boost_1_60_0/boost .

        # Setup cxxtest
        setup_lib cxxtest
        curl -LOv --user-agent "Mozilla/5.0" https://yer.dl.sourceforge.net/project/cxxtest/cxxtest/4.4/cxxtest-4.4.tar.gz
        tar -zxf cxxtest-4.4.tar.gz
        mv cxxtest-4.4/* .

        # Setup LAPACK
        setup_lib lapack
        curl -LOv --user-agent "Mozilla/5.0" https://www.netlib.org/lapack/lapack-3.6.0.tgz
        tar -zxf lapack-3.6.0.tgz
        mkdir lapack-build
        cd lapack-build
        cmake -G "Unix Makefiles" ../lapack-3.6.0
        make

    - name: Compile Yell
      run: |
        set -e
        mkdir yell-build
        cd yell-build
        cmake -G "Unix Makefiles" -DCMAKE_CXX_FLAGS:STRING="-O2" ..
        make