name: Compile YellProgram

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install gfortran/gcc
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install -y gfortran gcc

    - name: Compile levmar
      run: |
        set -e
        cd lib
        mkdir levmar
        cd levmar
        curl -LOv --user-agent "Mozilla/5.0" http://users.ics.forth.gr/~lourakis/levmar/levmar-2.6.tgz
        tar -zxf levmar-2.6.tgz
        mkdir levmar-build
        cd levmar-build
        cmake -G "Unix Makefiles" -DNEED_F2C:BOOL=0 -DBUILD_DEMO:BOOL=0 -DLAPACKBLAS_LIB_NAMES:STRING=" -framework accelerate" -DCMAKE_CONFIGURATION_TYPES:STRING="Release" ../levmar-2.6
        make
        cd ..
        mkdir include
        cp levmar-2.6/*.h include
        mkdir lib
        cp levmar-build/*.a lib

    - name: Setup HDF5
      run: |
        mkdir -p lib
        cd lib
        rm -rf hdf5-1.8.16  # This ensures the directory is cleared if it exists
        tar -xf ../hdf5-1.8.16.tar
        cd hdf5-1.8.16
        ./configure --prefix=$(pwd)/../hdf5-install 2> hdf5_configure_errors.log
        make 2> hdf5_make_errors.log
        make install 2> hdf5_make_install_errors.log
      shell: /usr/bin/bash -e {0}

    - name: Upload HDF5 Error Logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: hdf5-error-logs
        path: lib/hdf5-1.8.16/*.log

    - name: Setup boost
      run: |
        set -e
        cd lib
        mkdir boost
        cd boost
        curl -LOv --user-agent "Mozilla/5.0" https://yer.dl.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.zip
        unzip boost_1_60_0.zip
        mv boost_1_60_0/boost .

    - name: Setup cxxtest
      run: |
        set -e
        cd lib
        mkdir cxxtest
        cd cxxtest
        curl -LOv --user-agent "Mozilla/5.0" https://yer.dl.sourceforge.net/project/cxxtest/cxxtest/4.4/cxxtest-4.4.tar.gz
        tar -zxf cxxtest-4.4.tar.gz
        mv cxxtest-4.4/* .

    - name: Setup LAPACK
      run: |
        set -e
        cd lib
        mkdir lapack
        cd lapack
        curl -LOv --user-agent "Mozilla/5.0" http://netlib.org/lapack/lapack.tgz
        tar -zxf lapack.tgz
        mkdir lapack-build
        cd lapack-build
        cmake -G "Unix Makefiles" ../lapack-3.6.0
        make

    - name: Compile Yell
      run: |
        set -e
        mkdir yell-build
        cd yell-build
        cmake -G "MSYS Makefiles" -DCMAKE_CXX_FLAGS:STRING="-O2" ../yell
        make
