name: Compile YellProgram

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "12.0"

    - name: List LLVM folder
      run: |
       ls -la ${GITHUB_WORKSPACE}/llvm
       ls -la ${GITHUB_WORKSPACE}/llvm/include
       ls -la ${GITHUB_WORKSPACE}/llvm/include/c++
       ls -la ${GITHUB_WORKSPACE}/llvm/include/c++/13
       #/home/runner/work/Yell/Yell/llvm

    - name: "Check selected compiler"
      run: |
        cmake --help

    - name: Setup levmar
      run: |
        #set -e

        # Compile levmar
        mkdir lib/levmar
        cd lib/levmar
        curl -LOv --user-agent "Mozilla/5.0" http://users.ics.forth.gr/~lourakis/levmar/levmar-2.6.tgz
        tar -zxf levmar-2.6.tgz
        mkdir levmar-build
        cd levmar-build
        cmake -G "Unix Makefiles" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CONFIGURATION_TYPES:STRING="Release" -DNEED_F2C:BOOL=0 -DBUILD_DEMO:BOOL=0 ../levmar-2.6
        #-DCMAKE_LINKER=lld
        cmake --build .
        
    - name: Setup CXXtest
      run: |
        # Setup cxxtest
        mkdir lib/cxxtest
        cd lib/cxxtest
        curl -LOv --user-agent "Mozilla/5.0" https://yer.dl.sourceforge.net/project/cxxtest/cxxtest/4.4/cxxtest-4.4.tar.gz
        tar -zxf cxxtest-4.4.tar.gz
        mv cxxtest-4.4/* .

    - name: Setup LAPACK
      run: |
        # Setup LAPACK
        mkdir lib/lapack
        cd lib/lapack
        curl -LOv --user-agent "Mozilla/5.0" https://www.netlib.org/lapack/lapack-3.6.0.tgz
        tar -zxf lapack-3.6.0.tgz
        mkdir lapack-build
        cd lapack-build
        cmake -G "Unix Makefiles" ../lapack-3.6.0
        #cmake --build .

    - name: Setup and Compile Boost
      run: |
        mkdir -p lib/boost
        cd lib/boost
        curl -LOv --user-agent "Mozilla/5.0" https://yer.dl.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.zip
        unzip boost_1_60_0.zip
        cd boost_1_60_0

   # - name: List Boost headers
   #   run: |
   #     ls -la ${GITHUB_WORKSPACE}/lib/
   #     ls -la ${GITHUB_WORKSPACE}/lib/levmar
   #     ls -la ${GITHUB_WORKSPACE}/lib/levmar/levmar-build
        
#    - name: Check if file exists
#      run: |
#        ls -la ${GITHUB_WORKSPACE}/lib/cctbx_stubs/cctbx/sgtbx/
#        if [[ ! -f ${GITHUB_WORKSPACE}/lib/cctbx_stubs/cctbx/sgtbx/change_of_basis_op.cpp ]]; then
#          echo "File does not exist!"
#          exit 1
#        else
#          echo "File exists!"
#         fi

   

    - name: Compile Yell
      run: |
        #set -e
        #rm -rf yell-build
        mkdir yell-build
        cd yell-build
        cmake -G "Unix Makefiles"  -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS:STRING="-I${GITHUB_WORKSPACE}/lib/boost -I${GITHUB_WORKSPACE}/llvm/include" ..
        make
