name: Compile YellProgram

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install gfortran/gcc
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran gcc

    - name: Compile levmar
      run: |
        cd lib
        mkdir levmar
        cd levmar
        wget --no-check-certificate http://users.ics.forth.gr/~lourakis/levmar/levmar-2.6.tgz
        tar -zxf levmar-2.6.tgz
        mkdir levmar-build
        cd levmar-build
        cmake -G "Unix Makefiles" -DNEED_F2C:BOOL=0 -DBUILD_DEMO:BOOL=0 -DLAPACKBLAS_LIB_NAMES:STRING=" -framework accelerate" -DCMAKE_CONFIGURATION_TYPES:STRING="Release" ../levmar-2.6
        make
        cd ..
        mkdir include
        cp levmar-2.6/*.h include
        mkdir lib
        cp levmar-build/*.a lib

    - name: Setup HDF5
      run: |
        cd lib
        mkdir hdf5
        cd hdf5
        wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.6/src/hdf5-1.8.6.tar
        tar -xf hdf5-1.8.6.tar
        cd hdf5-1.8.6
        ./build-unix.sh
        cp -r * ../

    - name: Setup boost
      run: |
        cd lib
        mkdir boost
        cd boost
        wget --no-check-certificate http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.zip
        unzip boost_1_60_0.zip
        mv boost_1_60_0/boost .

    - name: Setup cxxtest
      run: |
        cd lib
        mkdir cxxtest
        cd cxxtest
        wget http://sourceforge.net/projects/cxxtest/files/cxxtest/4.4/cxxtest-4.4.tar.gz
        tar -zxf cxxtest-4.4.tar.gz
        mv cxxtest-4.4/* .
        
    - name: Setup LAPACK
      run: |
        cd lib
        mkdir lapack
        cd lapack
        wget http://netlib.org/lapack/lapack.tgz
        tar -zxf lapack.tgz
        mkdir lapack-build
        cd lapack-build
        cmake -G "Unix Makefiles" ../lapack-3.6.0
        make


    - name: Compile Yell
      run: |
        mkdir yell-build
        cd yell-build
        cmake -G "MSYS Makefiles" -DCMAKE_CXX_FLAGS:STRING="-O2" ../yell
        make
