name: Compile YellProgram

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compile HDF5 manually
      run: |
        mkdir -p lib/hdf5
        cd lib/hdf5
        tar -xf ../../hdf5-1.8.16.tar
        cd hdf5-1.8.16
        ./configure --prefix=/usr/local --enable-cxx
        make
        sudo make install

    - name: Setup Libraries
      run: |
        set -e
        
        setup_lib() {
          mkdir -p lib/$1
          cd lib/$1
        }

        # Compile levmar
        setup_lib levmar
        curl -LOv --user-agent "Mozilla/5.0" http://users.ics.forth.gr/~lourakis/levmar/levmar-2.6.tgz
        tar -zxf levmar-2.6.tgz
        mkdir levmar-build
        cd levmar-build
        cmake -G "Unix Makefiles" -DNEED_F2C:BOOL=0 -DBUILD_DEMO:BOOL=0 -DLAPACKBLAS_LIB_NAMES:STRING=" -framework accelerate" -DCMAKE_CONFIGURATION_TYPES:STRING="Release" ../levmar-2.6
        make
        #make install

        # Setup boost
        setup_lib boost
        curl -LOv --user-agent "Mozilla/5.0" https://yer.dl.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.zip
        unzip boost_1_60_0.zip
        mv boost_1_60_0/boost .
        make install

        # Setup cxxtest
        setup_lib cxxtest
        curl -LOv --user-agent "Mozilla/5.0" https://yer.dl.sourceforge.net/project/cxxtest/cxxtest/4.4/cxxtest-4.4.tar.gz
        tar -zxf cxxtest-4.4.tar.gz
        mv cxxtest-4.4/* .
        make install

        # Setup LAPACK
        setup_lib lapack
        curl -LOv --user-agent "Mozilla/5.0" https://www.netlib.org/lapack/lapack-3.6.0.tgz
        tar -zxf lapack-3.6.0.tgz
        mkdir lapack-build
        cd lapack-build
        cmake -G "Unix Makefiles" ../lapack-3.6.0
        make
        make install

        

    - name: List contents of directory
      run: ls -alh ${GITHUB_WORKSPACE}/lib/cctbx_stubs/cctbx/sgtbx/

    - name: Check if file exists
      run: |
        if [[ ! -f ${GITHUB_WORKSPACE}/lib/cctbx_stubs/cctbx/sgtbx/change_of_basis_op.cpp ]]; then
          echo "File does not exist!"
          exit 1
        else
          echo "File exists!"
        fi
        
    - name: Compile Yell
      run: |
        set -e
        rm -rf yell-build
        mkdir yell-build
        cd yell-build
        cmake --debug-output -G "Unix Makefiles" -DCMAKE_CXX_FLAGS:STRING="-I${GITHUB_WORKSPACE}/lib" -DCMAKE_INSTALL_PREFIX:PATH=${GITHUB_WORKSPACE}/install ..
        make
        make install